project:
  title: "Web Programming Notes"
  type: website
  output-dir: _site

toc: true
number-sections: true
editor: visual
#bibliography: references.bib

metadata-files: 
  - _website.yml
  - _book.yml
  
#profile:
#  default: website
#  group:
#    - [website, book]



format:
  html:
    theme: cosmo
    #css: style_bs4.css
    cover-image: cover.png
    number-sections: true
    toc: true
    toc-depth: 4
    code-fold: show #true
    code-summary: "TOGGLE the Code"
    code-overflow: scroll
    code-line-numbers: true
    code-copy: true #hover
    code-block-bg: "#383838"  #"#708090"
    code-block-border-left: "#31BAE9"
    highlight-style: ayu-dark #atom-one-dark #ayu-dark
    
#  pdf:
#    documentclass: scrreprt
#    toc: true
#    number-sections: true
#    colorlinks: true
    # default arrow highlight-style: github




